version: '3'

services:
  virtuoso:
    build: .
    container_name: Virtuoso
    ports:
      - "8890:8890"
      - "1111:1111"
    environment:
      - DBA_PASSWORD=pppp 
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.example.com/my-graph
    volumes:
      - /home/jorge/jorge/TFG/PruebasDocker/db:/data 